# Generated by Django 2.1 on 2018-08-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appinput', '0003_app_op_log_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='op_user',
        ),
        migrations.AddField(
            model_name='app',
            name='manage_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_user', to=settings.AUTH_USER_MODEL, verbose_name='APP管理员'),
        ),
    ]
