# Generated by Django 2.1 on 2018-08-11 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appinput', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='发布单编号')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='描述')),
                ('deploy_no', models.IntegerField(blank=True, default=0, null=True)),
                ('branch_build', models.CharField(blank=True, max_length=255, null=True)),
                ('jenkins_number', models.CharField(blank=True, max_length=255, null=True)),
                ('code_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_inc_tot', models.CharField(blank=True, choices=[('TOT', 'TOT'), ('INC', 'INC')], max_length=255, null=True, verbose_name='全量或增量部署')),
                ('deploy_type', models.CharField(blank=True, choices=[('deployall', '发布所有'), ('deploypkg', '发布程序'), ('deploycfg', '发布配置'), ('rollback', '回滚')], max_length=255, null=True, verbose_name='发布程序或配置')),
                ('salt_module_path', models.CharField(max_length=255, verbose_name='Salt APP路径')),
                ('nginx_url', models.URLField(blank=True, default=None, null=True, verbose_name='Tengine URL')),
                ('deploy_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布单状态')),
                ('deploy_progress', models.CharField(blank=True, max_length=32, null=True, verbose_name='发布单进度')),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_app', to='appinput.App', verbose_name='APP应用')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
