# Generated by Django 2.1 on 2018-08-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envx', '0001_initial'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploypool',
            name='salt_module_path',
        ),
        migrations.AddField(
            model_name='deploypool',
            name='env_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_env_name', to='envx.Env', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='is_build',
            field=models.BooleanField(default=False, verbose_name='软件是否编译成功'),
        ),
    ]
