# Generated by Django 2.1 on 2018-08-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20180818_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploypool',
            name='is_inc_tot',
            field=models.CharField(blank=True, choices=[('TOT', '全量部署'), ('INC', '增量部署')], max_length=255, null=True, verbose_name='全量或增量部署'),
        ),
    ]
