# Generated by Django 2.1 on 2018-09-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0004_auto_20180822_2037'),
        ('envx', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0005_auto_20180901_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作类型')),
                ('content', models.CharField(blank=True, max_length=1024, null=True, verbose_name='操作内容')),
                ('app_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_app', to='appinput.App', verbose_name='APP应用')),
                ('env_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_env_name', to='envx.Env', verbose_name='环境')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
