# Generated by Django 2.1 on 2018-08-11 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appinput', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('ip_address', models.CharField(max_length=24, verbose_name='IP地址')),
                ('salt_name', models.CharField(max_length=128, verbose_name='SaltStack minion')),
                ('port', models.CharField(max_length=100, verbose_name='端口')),
                ('app_user', models.CharField(blank=True, max_length=24, null=True, verbose_name='执行程序用户')),
                ('app_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='程序包发送路径')),
                ('salt_cmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='执行脚本salt路径')),
                ('deploy_version', models.CharField(blank=True, max_length=512, null=True, verbose_name='已部署版本')),
                ('deploy_status', models.CharField(blank=True, max_length=128, null=True, verbose_name='发布状态(Err,Suc)')),
                ('is_rollback', models.BooleanField(default=False)),
                ('init_param', models.CharField(blank=True, max_length=256, null=True, verbose_name='构建参数')),
                ('current_status', models.CharField(blank=True, default='正常', max_length=256, null=True, verbose_name='运行状态')),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_name', to='appinput.App', verbose_name='应用名')),
                ('op_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
