# Generated by Django 2.1 on 2018-08-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envx', '0001_initial'),
        ('serverinput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='deploy_version',
            new_name='history_deploy',
        ),
        migrations.AddField(
            model_name='server',
            name='env_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_env_name', to='envx.Env', verbose_name='环境'),
        ),
        migrations.AddField(
            model_name='server',
            name='file_trans_status',
            field=models.BooleanField(default=False, verbose_name='传递发布文件是否成功'),
        ),
    ]
