# Generated by Django 2.1 on 2018-10-20 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envx', '__first__'),
        ('appinput', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='发布单编号')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='描述')),
                ('deploy_no', models.IntegerField(blank=True, default=0, null=True)),
                ('branch_build', models.CharField(blank=True, max_length=255, null=True)),
                ('jenkins_number', models.CharField(blank=True, max_length=255, null=True)),
                ('code_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_inc_tot', models.CharField(blank=True, choices=[('TOT', '全量部署'), ('INC', '增量部署')], max_length=255, null=True, verbose_name='全量或增量部署')),
                ('deploy_type', models.CharField(blank=True, choices=[('deployall', '发布所有'), ('deploypkg', '发布程序'), ('deploycfg', '发布配置'), ('rollback', '回滚')], max_length=255, null=True, verbose_name='发布程序或配置')),
                ('is_build', models.BooleanField(default=False, verbose_name='软件是否编译成功')),
                ('nginx_url', models.URLField(blank=True, default=None, null=True, verbose_name='Tengine URL')),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_app', to='appinput.App', verbose_name='APP应用')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_create_user', to=settings.AUTH_USER_MODEL, verbose_name='创建用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeployStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, max_length=1024, verbose_name='备注')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('do_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作类型')),
                ('content', models.CharField(blank=True, max_length=1024, null=True, verbose_name='操作内容')),
                ('app_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_app', to='appinput.App', verbose_name='APP应用')),
                ('deploy_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_deploy', to='deploy.DeployPool', verbose_name='发布单')),
                ('env_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_env_name', to='envx.Env', verbose_name='环境')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='deploypool',
            name='deploy_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_pool_status', to='deploy.DeployStatus', verbose_name='发布单状态'),
        ),
        migrations.AddField(
            model_name='deploypool',
            name='env_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_env_name', to='envx.Env', verbose_name='环境'),
        ),
    ]
