# Generated by Django 2.1 on 2018-12-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploypool',
            name='name',
            field=models.CharField(max_length=100, verbose_name='发布单编号'),
        ),
    ]
