# Generated by Django 2.1 on 2018-08-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20180820_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploypool',
            name='deploy_progress',
        ),
    ]
