# Generated by Django 2.1 on 2018-09-01 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_remove_deploypool_deploy_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, max_length=1024, verbose_name='备注')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='deploypool',
            name='deploy_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deploy_pool_status', to='deploy.DeployStatus', verbose_name='发布单状态'),
        ),
    ]
