# Generated by Django 2.1 on 2018-09-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='deploy_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_deploy', to='deploy.DeployPool', verbose_name='发布单'),
        ),
    ]
