# Generated by Django 2.1 on 2018-10-20 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appinput', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('aid', models.IntegerField(unique=True, verbose_name='权限序号')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('action_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_action_name', to='rightadmin.Action', verbose_name='操作权限')),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_app_name', to='appinput.App', verbose_name='APP应用')),
                ('env_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_env_name', to='envx.Env', verbose_name='环境')),
                ('main_user', models.ManyToManyField(blank=True, related_name='pm_user', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'ordering': ('-change_date',),
                'abstract': False,
            },
        ),
    ]
