# Generated by Django 2.1 on 2018-08-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rightadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='env_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_env_name', to='envx.Env', verbose_name='环境'),
        ),
    ]
