# base image
FROM nginx:1.13-alpine

# MAINTANER
MAINTAINER author@demo.com

# cp custom nginx config and static folder
COPY default.conf /etc/nginx/conf.d/default.conf
COPY static /usr/local/manabe/static