# Generated by Django 2.1 on 2018-10-20 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('jenkins_job', models.CharField(max_length=255, verbose_name='JENKINS JOB名称')),
                ('git_url', models.CharField(max_length=512, verbose_name='Git地址')),
                ('build_cmd', models.CharField(max_length=512, verbose_name='编译命令')),
                ('is_restart_status', models.BooleanField(default=True, verbose_name='是否重启')),
                ('package_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='软件包名')),
                ('zip_package_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='压缩包名')),
                ('op_log_no', models.IntegerField(blank=True, default=0, null=True)),
                ('script', models.TextField(blank=True, max_length=65535, null=True, verbose_name='APP服务脚本')),
                ('manage_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_user', to=settings.AUTH_USER_MODEL, verbose_name='APP管理员')),
            ],
            options={
                'db_table': 'App',
                'ordering': ('-add_date',),
            },
        ),
    ]
