# Generated by Django 2.1 on 2018-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='dir_build_file',
            field=models.CharField(default='./', max_length=512, verbose_name='编译目录'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='build_cmd',
            field=models.CharField(default='./', max_length=512, verbose_name='编译命令'),
        ),
    ]
