# Generated by Django 2.1 on 2018-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinput', '0002_auto_20181020_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='script',
        ),
        migrations.AddField(
            model_name='app',
            name='script_url',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='app脚本链接'),
        ),
    ]
