# Generated by Django 2.1 on 2018-09-01 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rightadmin', '0003_auto_20180825_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='main_user',
            field=models.ManyToManyField(blank=True, related_name='pm_user', to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
    ]
